#!/bin/sh
set -e
HERE=$(dirname $0)
cd $HERE/../tls

FILE_ORIGINAL=key.pem
FILE_ENC=key.pem.enc
FILE_CLEAR=key.pem.copy

echo "Enter symmetric key: "
echo -n "key: "
read SYMKEY
export SYMKEY
openssl aes-256-cbc -d -md md5 -in $FILE_ENC -out $FILE_CLEAR -pass env:SYMKEY
echo "Wrote out the ssl private key to $FILE_CLEAR"
echo "Difference:"
echo "-----------"
diff $FILE_ORIGINAL $FILE_CLEAR
echo "-----------"
