#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
ROOT=$(realpath $HERE/..)

# https://gist.github.com/kennwhite/9918739
# https://www.bjornjohansen.no/encrypt-file-using-ssh-key
FILE_CLEAR=tls/key.pem
FILE_ENC=tls/key.pem.enc

if [ ! -f "$ROOT/$FILE_CLEAR" ]; then
    echo "Expected cleartext key file at $FILE_CLEAR"
    echo "Found cleartext key at tls/key.pem"
fi

# Generate the symmetric key and encrypt our ssl private key with it
SYMKEY=$(openssl rand -hex 32)
export SYMKEY

# Encrypt the key
openssl aes-256-cbc -md md5 \
        -in "$ROOT/$FILE_CLEAR" \
        -out "$ROOT/$FILE_ENC" \
        -pass "env:SYMKEY"

# Tell the user what to do
echo "Encrypted key is now saved as $FILE_ENC"
echo
echo "The key to decrypt this file, which you need to start vault, is"
echo "  $SYMKEY"
echo
echo "Distribute this key securely to people who can unlock the vault"
echo
echo "Delete the plaintext key at $FILE_CLEAR when happy"
