#!/bin/sh
set -e

HERE=$(dirname $0)

. "${HERE}/config"

export VAULT_ADDR=$SERVER_URL

KEY_SHARES=$(echo $KEY_OWNERS |  wc -w)
KEY_OWNER_STRING=$(echo $KEY_OWNERS | sed 's/ /, /g; s/\(.*\) /\1 and /')

vault operator init \
      -key-shares="$KEY_SHARES" \
      -key-threshold="$KEY_THRESHOLD"

cat <<EOF
Copy each of the keys above onto a USB key as individual files and
distribute one key and the root token to each of
$KEY_OWNER_STRING

After that, at least $KEY_THRESHOLD people need to unseal the vault using

  VAULT_ADDR=$SERVER_URL vault operator unseal

Then run ./setup
EOF
