#!/usr/bin/env bash
set -eu

HERE=$(dirname $0)

NAME_PREFIX="mrc-ide"
NAME_IMAGE="${NAME_PREFIX}-vault"
NAME_CONTAINER="${NAME_PREFIX}-vault"
VOLUME_DATA="${NAME_PREFIX}-vault-data"
VOLUME_LOGS="${NAME_PREFIX}-vault-logs"
VOLUME_TLS="${NAME_PREFIX}-vault-tls"

if docker container inspect $NAME_CONTAINER > /dev/null 2>&1; then
    echo "Error: docker container $NAME_CONTAINER is already running"
    exit 1
fi

if ! docker volume inspect "$VOLUME_DATA" > /dev/null 2>&1; then
    echo "Error: docker volume $VOLUME_DATA does not exist"
    echo
    echo "If this is a first time deployment, consider"
    echo
    echo "  docker volume create $VOLUME_DATA"
    exit 1
fi

if ! docker volume inspect "$VOLUME_TLS" > /dev/null 2>&1; then
    echo "Error: docker volume $VOLUME_TLS does not exist"
    echo
    echo "See the README.md for setting this up."
    exit 1
fi

if ! docker volume inspect "$VOLUME_LOGS" > /dev/null 2>&1; then
    docker volume create "$VOLUME_LOGS"
fi

docker run -d --rm \
       --cap-add=IPC_LOCK \
       --name "$NAME_CONTAINER" \
       -v "$VOLUME_DATA:/vault/file" \
       -v "$VOLUME_LOGS:/vault/logs" \
       -v "$VOLUME_TLS:/vault/tls" \
       -v "$PWD/vault.conf:/vault/config/vault.conf:ro" \
       -p "8200:8200" \
       hashicorp/vault:latest server -config /vault/config/vault.conf
