#!/usr/bin/env bash
if [[ ! -f "${PWD}/tls/key.pem" ]]; then
    echo "Expected to find file tls/key.pem"
    exit 1
fi

if [[ ! -f "${PWD}/tls/certificate.pem" ]]; then
    echo "Expected to find file tls/certificate.pem"
    exit 1
fi


VOLUME=mrc-ide-vault-tls
docker volume create $VOLUME
docker run --rm -v ${PWD}/tls:/src -v $VOLUME:/dst ubuntu cp /src/key.pem /dst
docker run --rm -v ${PWD}/tls:/src -v $VOLUME:/dst ubuntu cp /src/certificate.pem /dst
